api_platform:
    title: 'Simple REST-API for ecommerce'
    description: 'Test task by ECherepenya'
    version: 0.1
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/ApiResource']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
